-- 코드를 입력하세요
SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM((SALES * PRICE)) AS TOTAL_SALES
FROM BOOK_SALES BS
JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
# 2022년 1월의 도서 판매 데이터를 기준
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-01"
# 저자 별, 카테고리 별 
GROUP BY CATEGORY, A.AUTHOR_ID
# 저자 ID를 오름차순으로, 저자 ID가 같다면 카테고리를 내림차순 정렬
ORDER BY A.AUTHOR_ID, CATEGORY DESC


