-- 코드를 입력하세요
SELECT f.WAREHOUSE_ID, f.WAREHOUSE_NAME, f.ADDRESS,
if(f.FREEZER_YN is null, "N", f.FREEZER_YN) as REEZER_YN
FROM FOOD_WAREHOUSE f
WHERE f.WAREHOUSE_NAME like "%경기%"
ORDER BY f.WAREHOUSE_ID